### ISSUE TITLE
What hardware would you recommend for hacking on this code?

### ISSUE THREAD

**Issue by djbclark** [amowry/warbl#1]
In the README you mention the Adafruit ItsyBitsy 32u4-3.3V was used in prototyping, but unless there is a good reason not to, I'd prefer to use whatever you ended up going with in production. 

(I'm thinking it'd be fun to hack on wireless connectivity before I get together enough money to buy an actual WARBL, but even after I get it it'd probably be nice to not have to use the actual instrument for experiments.) In any case, this is a really awesome-looking product, and thank you SO MUCH for making the software side of it Free Software (from former FSF staff :-)

Related: https://warbl.xyz/phpbb/viewtopic.php?f=3&t=55&p=652&hilit=arduino#p652

**Comment by djbclark** [comment]
Nevermind (probably), took a look at the schematic, if I'm understanding correctly you are using a custom PCB with an ATmega32U4-MU chip. So yeah, getting the ItsyBitsy sounds way cheaper than going with the production solution :-)

https://warbl.xyz/WARBL_2.2%20Schematic.pdf

**Comment by amowry** [comment]
Yes, using the ItsyBitsy means you wouldn't be able to fit it in as small an enclosure as WARBL, but will be much easier for experimentation. WARBL uses the small QFN version of the MCU, which is a bit challenging to solder at home.
