### ISSUE TITLE
Proposal for new Jump Drop behaviour.

### ISSUE THREAD

**Issue by louis-barman** [amowry/warbl#12]
Below is the content of the document that I emailed to Andrew about the jump drop behaviour: his reply is given at the bottom of this issue: 

# Warbl Jump drop discussion 
For this discussion we will consider just the jump behaviour as exactly the same behaviour also applies when discussing a drop (although few people tongue a drop apart from when playing staccato).

### Bug in V2.0 UI
1. In the advanced Register Control Settings the Jump value ranges from 0 to 175. However it is not possible to set this to a number greater than 127 and for this value be retained by the Warbl.
1. It is not possible to completely turn off the jump behaviour even setting a value of 127  Tonguing the start of a low note causes an initial very rapid pressure rise which can be greater than 127.  It should be possible to turn off the Jump algorithm completely.

## Jump drop behaviour in v2.0.

The jump feature works by trying to predict the future as described below:

> _If the pressure has increased rapidly (since the last reading) and there's at least enough pressure to turn a note on, jump immediately to the second register._

However if the user always tongues all the notes when starting from silence then I don’t believe it is possible to detect accurately in advance whether the user is heading for the low octave or the high octave.

Another disadvantage of this method is that the user will not be able to adjust the settings if the user does not understand what side effect a bad value will have. I did not know to listen out for an unwanted octave high note when playing a low note. I kept trying to hear an effect when jumping straight to the high note. Also having four controls that the user can adjust is perhaps too many.
## Behaviour with Jump Drop disabled.
With the Jump drop feature completely disabled (by commenting out that code) then the users will never produce an unwanted high octave note without first crossing the high threshold . The only issue is when moving from silence straight to a high note there will always be a transient low note. I don’t find this a great problem for the following reasons:
I always tongue every note when starting from silence and so this note is very brief 
I always use the breath controller or volume controller and so the volume of this unwanted transient note when jumping (or dropping) will always be reduced and so it is not so audible. But it would still be annoying when using the Warbl to enter the musical notes in a notation program or when not using the breath/volume controller.

## Suggested new Jump Drop behaviour.
An alternative way of dealing with the unwanted jump/drop transients would be to delay making the decision until we definitely know whether it is going to be the low or high octave.  So only when we know definitely one way or the other would we send out the note-on. The disadvantage of this method is there would be a slight delay when starting from silence or dropping from the top octave. We would make a decision and send out the note-on as soon as one of the following conditions were met: 
For a jump to the top octave as soon as we pass the high threshold -- then output the high midi note-on.
If the rapid pressure rise starts to level out -- then we decide that this is a low note and output the low midi note-on.

An advantage of this method is that it could have a single easily understood setting -- the maximum number of mSec to wait before sending out a note-on. It should be stressed to the user that this is a maximum value that the note on might be delayed and often it would be much shorter.

When playing a high E with tonguing I get a value of  6 mSec when tonguing. This figure is found by measuring the time difference between the (unwanted) midi note-on for the low E and the high E midi note-on. I don’t believe the users would notice a delay this short. When not tonguing the high ‘E’ I get a much longer time of 108 mSec.

# Andrews reply:

> I just read the document—I increased the range of the jump slider to 175 a few weeks ago when I was playing with jump/drop, and I forgot that it’s limited to 127. Thanks for noticing that!

> I think your suggestion for jump/drop sounds fine, and it’s pretty much what I had in mind based on your earlier comments. If you’d like to work on it, that’s fine, or I can work on it after you hand everything over to me.

**Comment by louis-barman** [comment]
I have had some success with implementing this and it seems to work quite well in my opinion. The jump time i have set to 12 mS and the drop time 100 mS. Please remember that is the absolute maximum time to delay before switching octave. If the pressure either crosses top register threshold (for a jump) or crosses the silence threshold (for a drop) or the pressure levels out (or reverses) you will get the new register immediately. 

I will push my code to my repo soon and when I have everything in place I will generate a pull request.

**Comment by amowry** [comment]
Thanks Louis! I'll look forward to trying this.

**Comment by louis-barman** [comment]
The code is now pushed to my repo  the branch `wip/debounce` if you want to try it out. see https://github.com/louis-barman/warbl/tree/wip/debounce

I have moved my code into standard c++ files called `register_ctrl.cpp` and also added some unit tests using GoogleTest in a new directory  see https://github.com/louis-barman/warbl/blob/wip/debounce/tests/register_ctrl_test.cpp. This makes it much easier to write the code since you can develop and test the code on a PC and then it worked first time when I came to try it out on the Warbl.

I have reused the following controls.

* `Jump Time` the max time allowed to jump in mSec (recommend value 12) 
* `Drop_Time` the max time allowed to drop in mSec (recommend value 100) 
* '`Drop` now used for hysteresis   0 for OFF, 10 for LOW, 25 for MEDIUM, 40 for HIGH
* `Jump` now controls the debounce delay (filter transient notes [NUMBER_FIELD] mSec) (8 mSec is recommend)

This code changes has removed a lot (but not all) of the unwanted transient notes. see 
![warbl lb jump 100](https://user-images.githubusercontent.com/5164566/140623749-b1282dbe-dfe8-4fe6-a8ff-1427807648bd.png)


The code is not quite ready for to be integrated yet. I'll generate a pull request when it is ready.

**Comment by amowry** [comment]
Great, thanks! That's ideal that we can reuse the controls. Are you reusing the variables too so they get stored/reloaded from EEPROM?

**Comment by amowry** [comment]
I just tested the hysteresis, debounce delay, and jump/drop, and it all seems good to me. Maybe the only major thing left is fixing the pitch expression? I forget if I was going to do that or if you were (?).

**Comment by louis-barman** [comment]
Sorry for the slow reply. I have re-used all the variables so they do get stored/reloaded from EEPROM but I hacked the code to make it work. I'll add a comment to my code `// amowry PLEASE CHANGE AND FIX THIS' so you know where you will need to make changes. I am planning to fixing the pitch expression myself.

Also one of the things that I discovered is that your pressure readings interrupts are not a regular tick once every 1 mSec  but are not precisely controlled and so take longer than 1 mSec. I need to measure the time accurately but it may be once every 1.25 mSec with lots of jitter . This is causing me problems because I was using a count of the pressure readings to measure the time.  There are two ways this can be fixed:

1. Use the call to `millis()` to accurately measure the time.
2. Add a fudge factor jump/drop and debounce delay times to make them roughly match the time in mSec that the users has entered.

Probably 1. is the best fix.

Also Andrew did you try running any of the tests on Windows? I think you should just need to open the `CMakeLists.txt` using Visual Studio for windows. And it should all just work.

Unfortunately I am going to be busy with something else for the next two weeks and  so these changes will have to wait until then. But I will get them done as soon as I can.

**Comment by amowry** [comment]
Thanks! Yes, 1.25 mS sounds about right. As you probably saw in the code, I add a delay of a few hundred uS to conserve power a little bit. That might also change in the future, so I probably wouldn't use it for measuring time for anything critical. I'm not too surprised that there's jitter either,  so I agree, millis() is probably best.

I haven't tried the test in Windows, partly from lack of time but also because I've never even used Visual Studio :). So far I've tried to confine everything to Arduino just because my skill level is so limited.

No hurry on the timing. A we approach the holidays I expect I won't be able to spend time on this until the new year.

**Comment by amowry** [comment]
Louis, have you had a chance to finalize your additions to code? I'd love to include them in the next release. Thanks!

**Comment by amowry** [comment]
I've added this and the key delay to the 2.1 firmware, which I plan to release soon. I decided not to include the hysteresis, because of the issue with calculating expression and the highest notes playing at unwanted times. It may be something we could revisit in the future. Thanks for these additions, Louis!
