### ISSUE TITLE
Compatibility with Expert Sleepers FH-2

### ISSUE THREAD

**Issue by bxjx** [amowry/warbl#3]
Hello! I'm using the Warbl with the Expert Sleepers FH-2. It's a very popular eurorack module that functions as a host or device to convert midi to control voltage (https://www.expert-sleepers.co.uk/fh2.html).

Unfortunately the FH-2 does not detect the Warbl as a device. I chatted with the main developer of the FH-2 (who mentioned that they might reach out to you and who is also a wind player!). I gave them a dump of a usb probe.

They mentioned:
```
 I don't know for sure if they're what's tripping up the FH-2.

Endpoint 0x04 - Bulk Output   
                Address:   0x04  (OUT)
Endpoint 0x85 - Bulk Input   
                Address:   0x85  (IN)

Usually the MIDI endpoints have addresses 0x01 and 0x81.
```

I appreciate that this might have nothing to do with Warbl, but I was just wondering if you had any advice on debugging this or if there was anything I might try to test the compatibility e.g. changing those values in firmware? Sorry, I don't have any Arduino experience, so this might be a ridiculous suggestion.

Again, thanks so much! Loving the product!

**Comment by amowry** [comment]
Yes, they did get in touch with me, and I'm sending them a WARBL to test. This is the first MIDI host that I've heard of that WARBL doesn't work with-- it could be something with the endpoints, as I'm not too knowledgeable about those. Hopefully we'll be able to get it working and you'll be able to fix it with another firmware update. I'll keep you posted.

**Comment by bxjx** [comment]
Good to hear! Looking forward to using the combo. Thanks @amowry.

**Comment by bxjx** [comment]
Also feel free to close the issue, as this might be something entirely to do with the FH-2. I can send you my email for any updates. Having said that, the issue could be useful as a resource for anyone else searching the internet who is researching using this combo tho. I leave with you 😄

**Comment by amowry** [comment]
I believe we've resolved the issue. The latest firmware on the WARBL Documentation page contains the fix:

[https://warbl.xyz/documentation.html](url)

There are also instructions there for installing it, but just let me know if you have any questions. I believe Expert Sleepers may also contact you about it. Thanks for finding this issue!

**Comment by bxjx** [comment]
Thanks @amowry! I'll give it a go shortly and report back.

Would it be possible to combine this firmware update with the multi channel firmware you published for me before?

**Comment by bxjx** [comment]
The version up on the website didn't work for me. The version that Andrew from Expert Sleepers sent through did tho! It was named `WARBL_1.8_descriptor_fix.ino.hex`. Great work! Thanks so much @amowry !

And yes, it would be great if I could get a firmware that combines this fix with the different channels per instrument firmware!

**Comment by amowry** [comment]
Sure, sorry, I forgot about that. Here's that one:

[https://github.com/amowry/warbl/blob/master/WARBL_1.8_multiple_MIDI_channels.ino.hex](url)

I'll double-check the version on the web site.

**Comment by amowry** [comment]
I had gotten the link on the web site wrong and linked to an old file, but it's fixed now. Thanks for letting me know about that!

**Comment by bxjx** [comment]
Worked perfectly! Thanks again for being so responsive!
