### ISSUE TITLE
When moving from low B to high D a bottom D note on is always sent.

### ISSUE THREAD

**Issue by louis-barman** [amowry/warbl#7]
When using overblowing and moving from low B to high D  (B4 to D5) it should be possible to go directly to the high D without a bottom D (D5) sounding provided the pressure is above the D overblow threshold. Thanks to the use of the multiplier the pressure to play the  low B can be above the D overblow threshold in which case the low D should not sound.

Fortunately  I have found where the problem lies in the code. When a new note has been detected and `newNote` is set. see the the following line :
```
        newNote = tempNewNote; //update the next note if the fingering pattern is valid
```

The problem happens if `get_state()` is then not called or it finishes early. This can happen if  `sensorDataReady` is false and also if 'sensorValue == sensorValue2' then `get_state()` finishes early which means that the `newState` is not calculated before the midi note on is sent.

**Comment by amowry** [comment]
I tested this a bit today and although I'm not sure I'm able to reproduce this issue, I do see your point-- it hadn't occurred to me that the state could need to be recalculated because the note had changed rather than because the pressure had changed. I've added your fix to my codebase, which I'll push after I fix a few more things.

**Comment by amowry** [comment]
I think there were a few different issue here-- the delay introduced by the jump/drop behavior was preventing the register from being recalculated right away, causing brief upper register notes to be played erroneously with certain fingering sequences. I added a special case to eliminate this in addition to your fix above.
