### ISSUE TITLE
Too little overblowing pressure will play the very top  D (D5).  

### ISSUE THREAD

**Issue by louis-barman** [amowry/warbl#9]
**EDIT: RETESTED and this is not in the current version 2.0** (it  only applies to the new hysteresis code)

With the overblowing option set and blowing lightly and play a high D (D5)  with all holes covered apart from the L1 hole. Then if we increase the pressure to overblow we move to the very top D (D6) . When using the multiplier this should be the hardest note reach  requiring  the maximum pressure to reach but instead it is the easiest note to play when overblowing which is a bug in my opinion.

So if all fingers are covered and we play the bottom low D (D4) then increasing the pressure should move the the high D (D5) which should be an easy note to reach. Then lifting the finger off the L1 hole should have no effect. However increasing the pressure further ( when using the multiplier)  should only then play the very top D (D6) which should be the note requiring the most pressure to reach.

**Comment by amowry** [comment]
I'm having trouble reproducing this one too-- just to verify, you're using the tin whistle fingering, correct? Are you using the default settings for the multiplier? When I graph the pressure required to overblow all the notes in the scale, the D6 requires more pressure than any other note. When I try to reproduce this using your description above, i.e. playing D4, then overblowing to play D5, and finally removing the L1 finger, it always stays on D5 for me unless I then add considerably more pressure to overblow to D6. It makes me wonder if we're using different settings and this bug only crops up with certain settings?

**Comment by louis-barman** [comment]
Closing this was a problem in my code that I have just fixed.
